<?php if(Mage::getStoreConfig("slideshow/general/enable")): ?>
<?php
	$bannerCollections = Mage::getModel('slideshow/slideshow')
	->getCollection()
	->addFieldToFilter(
		array('stores', 'stores'),
		array(
			array('finset'=>Mage::app()->getStore()->getId()), 
			array('eq'=>'0'))
	)
	->addFieldToFilter('filename', array('neq' => ''))
	->addFieldToFilter('status', array('eq' => '1'))->setOrder("sort_order","ASC");	
?>
<?php if(count($bannerCollections) > 0): ?>

<script src="<?php echo $this->getJsUrl('slideshow/jquery.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slideshow/jquery.mobile.customized.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slideshow/jquery.easing.1.3.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slideshow/camera.min.js'); ?>" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl('slideshow/css/camera.css'); ?>" type="text/css" rel="stylesheet"></link>

<style type="text/css">
.fluid_container {
	margin: 0 auto;
	max-width: <?php echo Mage::getStoreConfig("slideshow/general/width"); ?>px;
	width: 100%;
}
</style>
<div class="fluid_container">
<div class="camera_wrap <?php echo Mage::getStoreConfig("slideshow/general/skin"); ?>" id="camera_wrap_1">
        
<?php foreach ($bannerCollections as $item): ?>
		<div data-thumb="<?php echo str_replace("/slides/","/slides/thumbs/", Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item->getFilename() )?>" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item->getFilename() ?>" data-link="<?php echo $item->getSlideUrl() ?>" data-target="<?php echo $item->getSlideTarget() ?>">
			<?php 
			if(Mage::getStoreConfig("slideshow/title/enable_title") == "1")
			{		
			?>
            <div class="<?php echo Mage::getStoreConfig("slideshow/title/fx_title")?>" style="bottom: 0;display: <?php echo $stat_description;?>;position: absolute;width: <?php echo Mage::getStoreConfig("slideshow/title/width_title")?>%;height: <?php echo Mage::getStoreConfig("slideshow/title/height_title")?>%;
	margin-left: <?php echo Mage::getStoreConfig("slideshow/title/margin_title")?>%">
            <div style="opacity:<?php echo Mage::getStoreConfig("slideshow/title/opacity_title")?>;border-radius:<?php echo Mage::getStoreConfig("slideshow/title/border_radius_title")?>px;-webkit-border-radius: <?php echo Mage::getStoreConfig("slideshow/title/border_radius_title")?>px;
-moz-border-radius: <?php echo Mage::getStoreConfig("slideshow/title/border_radius_title")?>px; background-color: #<?php echo Mage::getStoreConfig("slideshow/title/title_bg_color")?>; padding: 10px 10px; font-size: <?php echo Mage::getStoreConfig("slideshow/title/font_size_title")?>px; color: #<?php echo Mage::getStoreConfig("slideshow/title/font_color_title")?>;">			
                <b><?php echo $item->getTitle() ?></b>
            </div>				
            </div>	
       <?php }?>			
			<?php 
			if(Mage::getStoreConfig("slideshow/description/enable_description") == "1")
			{			
			?>
            <div class="<?php echo Mage::getStoreConfig("slideshow/description/fx_description")?>" style="bottom: 0;display: <?php echo $stat_description;?>;position: absolute;width: <?php echo Mage::getStoreConfig("slideshow/description/width_description")?>%;height: <?php echo Mage::getStoreConfig("slideshow/description/height_description")?>%;
	margin-left: <?php echo Mage::getStoreConfig("slideshow/description/margin_description")?>%">
            <div style="opacity:<?php echo Mage::getStoreConfig("slideshow/description/opacity_description")?>;border-radius:<?php echo Mage::getStoreConfig("slideshow/description/border_radius_description")?>px;-webkit-border-radius: <?php echo Mage::getStoreConfig("slideshow/description/border_radius_description")?>px;
-moz-border-radius: <?php echo Mage::getStoreConfig("slideshow/description/border_radius_description")?>px; background-color: #<?php echo Mage::getStoreConfig("slideshow/description/description_bg_color")?>; padding: 10px 10px; font-size: <?php echo Mage::getStoreConfig("slideshow/description/font_size_description")?>px; color: #<?php echo Mage::getStoreConfig("slideshow/description/font_color_description")?>;">			
                <?php echo $item->getContent() ?>
            </div>				
            </div>
       <?php } ?>
        </div>
<?php endforeach;?>
</div>
</div>

<script type="text/javascript">
//jQuery.noConflict();
jQuery(document).ready(function(){
	jQuery('#camera_wrap_1').camera({
		alignment: 'center',
		autoAdvance: true,
		mobileAutoAdvance: true,
		barDirection: '<?php echo Mage::getStoreConfig("slideshow/general/bar_direction"); ?>',
		barPosition: 'bottom',
		cols: <?php echo Mage::getStoreConfig("slideshow/advance/cols"); ?>,
		easing: '<?php echo Mage::getStoreConfig("slideshow/advance/easing"); ?>',
		mobileEasing: '<?php echo Mage::getStoreConfig("slideshow/advance/easing"); ?>',
		overlayer: false,
		pagination: <?php echo Mage::getStoreConfig("slideshow/general/pagination"); ?>,
		playPause: <?php echo Mage::getStoreConfig("slideshow/general/play_pause"); ?>,
		pauseOnClick: <?php echo Mage::getStoreConfig("slideshow/general/pause_on_click"); ?>,
		pieDiameter: 30,
		piePosition: '<?php echo Mage::getStoreConfig("slideshow/general/pie_position"); ?>',
		portrait: <?php echo Mage::getStoreConfig("slideshow/general/portrait"); ?>,
		rows: <?php echo Mage::getStoreConfig("slideshow/advance/rows"); ?>,
		slicedRows: <?php echo Mage::getStoreConfig("slideshow/advance/sliced_rows"); ?>,
		slicedCols: <?php echo Mage::getStoreConfig("slideshow/advance/sliced_cols"); ?>,
		fx: '<?php echo Mage::getStoreConfig("slideshow/advance/fx"); ?>',
		mobileFx: '<?php echo Mage::getStoreConfig("slideshow/advance/fx"); ?>',
		gridDifference: <?php echo Mage::getStoreConfig("slideshow/advance/grid_difference"); ?>,
		height: '<?php echo Mage::getStoreConfig("slideshow/general/height"); ?>',
		hover: <?php echo Mage::getStoreConfig("slideshow/general/hover"); ?>,
		slideOn: '<?php echo Mage::getStoreConfig("slideshow/general/slide_on"); ?>',
		thumbnails: <?php echo Mage::getStoreConfig("slideshow/general/thumbnails"); ?>,
		time: <?php echo Mage::getStoreConfig("slideshow/advance/time"); ?>,
		transPeriod: <?php echo Mage::getStoreConfig("slideshow/advance/trans_period"); ?>,
		loader: '<?php echo Mage::getStoreConfig("slideshow/loader/loader"); ?>',
		loaderColor: '#<?php echo Mage::getStoreConfig("slideshow/loader/loader_color"); ?>',
		loaderBgColor: '#<?php echo Mage::getStoreConfig("slideshow/loader/loader_bg_color"); ?>',
		loaderOpacity: <?php echo Mage::getStoreConfig("slideshow/loader/loader_opacity"); ?>,
		loaderPadding: 2,
		loaderStroke: <?php echo Mage::getStoreConfig("slideshow/loader/loader_stroke"); ?>, //loader thickness
		minHeight: '',
		navigation: <?php echo Mage::getStoreConfig("slideshow/general/navigation"); ?>,
		navigationHover: <?php echo Mage::getStoreConfig("slideshow/general/navigation_on_hover"); ?>,
		mobileNavHover: <?php echo Mage::getStoreConfig("slideshow/general/navigation_on_hover"); ?>,
		opacityOnGrid: <?php echo Mage::getStoreConfig("slideshow/advance/opacity_on_grid"); ?>,

	});
});

</script>
<?php endif; ?>
<?php endif; ?>